services:
  - type: web
    name: tcf-pricing-tool
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn "app:create_app()" --config gunicorn.conf.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: RENDER
        value: true
    disk:
      name: tcf-pricing-data
      mountPath: /opt/render/project/src/data
      sizeGB: 5 